"""phase 3 core domain

Problems, suggestions, teams, applications, projects and stage submissions.

Two hand edits to the autogenerated output:
  * `problems.suggestion_id` ↔ `problem_suggestions.published_problem_id` is a
    cycle, so that one FK is added after both tables exist and dropped before
    either goes away.
  * autogenerate creates the native enum types implicitly with the tables but
    never drops them; downgrade drops all eight so a cycle can be repeated.

Revision ID: 8c64f64da439
Revises: ed4c1cb3623b
Create Date: 2026-08-12 18:46:50.206604+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '8c64f64da439'
down_revision: str | None = 'ed4c1cb3623b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_drafts',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_problem_drafts_created_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_problem_drafts_institution_id_institutions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_drafts'))
    )
    op.create_index('ix_problem_drafts_created_by', 'problem_drafts', ['created_by'], unique=False)
    op.create_table('problems',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('current_challenge', sa.Text(), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('tools', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('allow_individual', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('base_credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='problem_status'), nullable=False),
    sa.Column('suggestion_id', sa.UUID(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_credits >= 0', name=op.f('ck_problems_base_credits_non_negative')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_problems_dates_ordered')),
    sa.CheckConstraint('team_size BETWEEN 1 AND 6', name=op.f('ck_problems_team_size_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_problems_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_problems_institution_id_institutions'), ondelete='RESTRICT'),
    # fk_problems_suggestion_id_problem_suggestions is added below, once
    # problem_suggestions exists.
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems'))
    )
    op.create_index('ix_problems_created_by_status', 'problems', ['created_by', 'status'], unique=False)
    op.create_index('ix_problems_institution_id_status_department', 'problems', ['institution_id', 'status', 'department'], unique=False)
    op.create_table('problem_bookmarks',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_problem_bookmarks_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_problem_bookmarks_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'problem_id', name=op.f('pk_problem_bookmarks'))
    )
    op.create_table('problem_suggestions',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('mentor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_mentor_review', 'changes_requested', 'approved', 'published', 'rejected', name='problem_suggestion_status'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('importance', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=False),
    sa.Column('reference_links', postgresql.ARRAY(sa.String(length=500)), nullable=False),
    sa.Column('mentor_feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_problem_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_problem_suggestions_institution_id_institutions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], name=op.f('fk_problem_suggestions_mentor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_problem_id'], ['problems.id'], name=op.f('fk_problem_suggestions_published_problem_id_problems'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_problem_suggestions_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_suggestions'))
    )
    op.create_index('ix_problem_suggestions_mentor_id_status', 'problem_suggestions', ['mentor_id', 'status'], unique=False)
    op.create_index('ix_problem_suggestions_student_id', 'problem_suggestions', ['student_id'], unique=False)
    # The second half of the suggestion ↔ problem cycle.
    op.create_foreign_key(
        'fk_problems_suggestion_id_problem_suggestions',
        'problems',
        'problem_suggestions',
        ['suggestion_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('teams',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pitch', sa.Text(), nullable=False),
    sa.Column('leader_id', sa.UUID(), nullable=False),
    sa.Column('looking_for', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_teams_institution_id_institutions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], name=op.f('fk_teams_leader_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_teams_problem_id_problems'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index('ix_teams_problem_id', 'teams', ['problem_id'], unique=False)
    op.create_table('projects',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('mentor_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('selection_status', sa.Enum('not_reviewed', 'changes_requested', 'selected', 'not_selected', name='selection_status'), nullable=False),
    sa.Column('selection_feedback', sa.Text(), nullable=True),
    sa.Column('selection_decided_by', sa.UUID(), nullable=True),
    sa.Column('selection_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_projects_institution_id_institutions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], name=op.f('fk_projects_mentor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_projects_problem_id_problems'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selection_decided_by'], ['users.id'], name=op.f('fk_projects_selection_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_projects_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index('ix_projects_institution_id_problem_id', 'projects', ['institution_id', 'problem_id'], unique=False)
    op.create_index('ix_projects_mentor_id', 'projects', ['mentor_id'], unique=False)
    op.create_index('ix_projects_team_id', 'projects', ['team_id'], unique=False)
    op.create_index('uq_projects_active_team', 'projects', ['problem_id', 'team_id'], unique=True, postgresql_where='team_id IS NOT NULL AND deleted_at IS NULL')
    op.create_table('team_invitations',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='invitation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_team_invitations_invited_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_invitations_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_invitations'))
    )
    op.create_index('ix_team_invitations_email_status', 'team_invitations', ['email', 'status'], unique=False)
    op.create_index('uq_team_invitations_pending', 'team_invitations', ['team_id', 'email'], unique=True, postgresql_where="status = 'pending'")
    op.create_table('team_join_requests',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='join_request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_team_join_requests_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_join_requests_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_join_requests'))
    )
    op.create_index('ix_team_join_requests_team_id_status', 'team_join_requests', ['team_id', 'status'], unique=False)
    op.create_index('uq_team_join_requests_pending', 'team_join_requests', ['team_id', 'student_id'], unique=True, postgresql_where="status = 'pending'")
    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_team_members_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_team_members_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('student_id', 'problem_id', name='uq_team_members_student_id_problem_id'),
    sa.UniqueConstraint('team_id', 'student_id', name='uq_team_members_team_id_student_id')
    )
    op.create_index('ix_team_members_student_id', 'team_members', ['student_id'], unique=False)
    op.create_table('applications',
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('idea_summary', sa.Text(), nullable=False),
    sa.Column('approach', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'withdrawn', name='application_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_applications_problem_id_problems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_applications_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_applications_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_applications_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('project_id', name=op.f('uq_applications_project_id'))
    )
    op.create_index('ix_applications_problem_id_status', 'applications', ['problem_id', 'status'], unique=False)
    op.create_index('ix_applications_student_id', 'applications', ['student_id'], unique=False)
    op.create_index('uq_applications_active', 'applications', ['problem_id', 'student_id'], unique=True, postgresql_where="status = 'active'")
    op.create_table('stage_submissions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('idea', 'poc', 'final', name='submission_stage'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_review', 'changes_requested', 'approved', 'rejected', name='submission_status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_strengths', sa.Text(), nullable=True),
    sa.Column('review_weaknesses', sa.Text(), nullable=True),
    sa.Column('review_suggestions', sa.Text(), nullable=True),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_stage_submissions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_stage_submissions_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_submissions')),
    sa.UniqueConstraint('project_id', 'stage', name='uq_stage_submissions_project_id_stage')
    )
    op.create_index('ix_stage_submissions_status_stage', 'stage_submissions', ['status', 'stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stage_submissions_status_stage', table_name='stage_submissions')
    op.drop_table('stage_submissions')
    op.drop_index('uq_applications_active', table_name='applications', postgresql_where="status = 'active'")
    op.drop_index('ix_applications_student_id', table_name='applications')
    op.drop_index('ix_applications_problem_id_status', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_team_members_student_id', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index('uq_team_join_requests_pending', table_name='team_join_requests', postgresql_where="status = 'pending'")
    op.drop_index('ix_team_join_requests_team_id_status', table_name='team_join_requests')
    op.drop_table('team_join_requests')
    op.drop_index('uq_team_invitations_pending', table_name='team_invitations', postgresql_where="status = 'pending'")
    op.drop_index('ix_team_invitations_email_status', table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index('uq_projects_active_team', table_name='projects', postgresql_where='team_id IS NOT NULL AND deleted_at IS NULL')
    op.drop_index('ix_projects_team_id', table_name='projects')
    op.drop_index('ix_projects_mentor_id', table_name='projects')
    op.drop_index('ix_projects_institution_id_problem_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_teams_problem_id', table_name='teams')
    op.drop_table('teams')
    # Break the cycle before either side is dropped.
    op.drop_constraint(
        'fk_problems_suggestion_id_problem_suggestions', 'problems', type_='foreignkey'
    )
    op.drop_index('ix_problem_suggestions_student_id', table_name='problem_suggestions')
    op.drop_index('ix_problem_suggestions_mentor_id_status', table_name='problem_suggestions')
    op.drop_table('problem_suggestions')
    op.drop_table('problem_bookmarks')
    op.drop_index('ix_problems_institution_id_status_department', table_name='problems')
    op.drop_index('ix_problems_created_by_status', table_name='problems')
    op.drop_table('problems')
    op.drop_index('ix_problem_drafts_created_by', table_name='problem_drafts')
    op.drop_table('problem_drafts')
    # ### end Alembic commands ###

    # The tables carried these types in; without an explicit drop the next
    # upgrade fails with "type problem_status already exists".
    for enum_name in (
        "problem_status",
        "problem_suggestion_status",
        "submission_stage",
        "submission_status",
        "selection_status",
        "application_status",
        "invitation_status",
        "join_request_status",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
