"""credit rules learn percent of award (ADR-10)

An amendment to the Phase 5A Credit Engine, not a phase of its own.

`credit_rules` learns a second way to price an event: `percent_of_award`, a
whole-number percentage of the award that triggered it. A rule prices an event
one way or the other, never both, which is what the two check constraints say.

Hand written rather than autogenerated, because the seed matters as much as the
column. Under the approved REPLACE policy the flat
`MENTORED_PROJECT_COMPLETED` rule is deactivated — never deleted, because the
ledger lines it already paid are read back through it — and
`MENTOR_AWARD_SHARE` at 50% takes over. Nothing is backfilled and no existing
`credit_transactions` row is touched: a mentor credited under the old rule
keeps exactly what they were credited.

`downgrade` restores the previous shape, so it deletes the percentage rule
before making `points` NOT NULL again. Any other percentage rule an operator
added by hand would have to go the same way first.

Revision ID: 9f41c07a2d18
Revises: 5b908971eef5
Create Date: 2026-08-16 11:20:00.000000+00:00
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '9f41c07a2d18'
down_revision: str | None = '5b908971eef5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ROLE_ENUM = postgresql.ENUM(
    'student', 'faculty', 'admin', 'principal', name='role_enum', create_type=False
)

FLAT_MENTORSHIP = "UPDATE credit_rules SET active = :active WHERE event_type = 'MENTORED_PROJECT_COMPLETED'"


def upgrade() -> None:
    op.add_column('credit_rules', sa.Column('percent_of_award', sa.Integer(), nullable=True))
    op.alter_column('credit_rules', 'points', existing_type=sa.Integer(), nullable=True)
    op.create_check_constraint(
        op.f('ck_credit_rules_price_exclusive'),
        'credit_rules',
        '(points IS NULL) <> (percent_of_award IS NULL)',
    )
    op.create_check_constraint(
        op.f('ck_credit_rules_percent_is_a_percentage'),
        'credit_rules',
        'percent_of_award IS NULL OR percent_of_award BETWEEN 0 AND 100',
    )
    _replace_the_flat_mentorship_rule()


def _replace_the_flat_mentorship_rule() -> None:
    """The share rule in, the flat rule out — one policy, not two (D1, D3)."""
    rules = sa.table(
        'credit_rules',
        sa.column('id', sa.UUID()),
        sa.column('role', ROLE_ENUM),  # bind as role_enum, not text
        sa.column('event_type', sa.String()),
        sa.column('points', sa.Integer()),
        sa.column('percent_of_award', sa.Integer()),
        sa.column('description', sa.String()),
        sa.column('active', sa.Boolean()),
    )
    op.bulk_insert(
        rules,
        [
            {
                'id': uuid.UUID('a1d1f6c2-0a51-4f0e-9c4a-2f0b1d5e7a05'),
                'role': 'faculty',
                'event_type': 'MENTOR_AWARD_SHARE',
                'points': None,
                'percent_of_award': 50,
                'description': 'Half of what a mentored project is awarded, paid to its '
                'mentor when the award completes the project.',
                'active': True,
            },
        ],
    )
    op.execute(sa.text(FLAT_MENTORSHIP).bindparams(active=False))


def downgrade() -> None:
    op.execute(sa.text(FLAT_MENTORSHIP).bindparams(active=True))
    op.execute(sa.text("DELETE FROM credit_rules WHERE percent_of_award IS NOT NULL"))
    op.drop_constraint(
        op.f('ck_credit_rules_percent_is_a_percentage'), 'credit_rules', type_='check'
    )
    op.drop_constraint(op.f('ck_credit_rules_price_exclusive'), 'credit_rules', type_='check')
    op.alter_column('credit_rules', 'points', existing_type=sa.Integer(), nullable=False)
    op.drop_column('credit_rules', 'percent_of_award')
