"""phase 5a credit engine

Awards, the ledger and the rule table.

Two hand edits to the autogenerated output:

* `role_enum` already exists (it was created with `users`), so `credit_rules`
  reuses the type instead of trying to create it a second time.
* the V1 rules are seeded here — `GET /credits/rules` reads them, and ADR-5
  requires rules to be configuration rows rather than hardcoded logic. Points
  come from the frozen frontend fixture `mocks/credits.ts::CREDIT_RULES`.

Revision ID: 3b73dfca841a
Revises: 8c64f64da439
Create Date: 2026-08-13 10:59:10.752160+00:00
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '3b73dfca841a'
down_revision: str | None = '8c64f64da439'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ROLE_ENUM = postgresql.ENUM(
    'student', 'faculty', 'admin', 'principal', name='role_enum', create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_rules',
    sa.Column('role', ROLE_ENUM, nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_rules'))
    )
    op.create_index('ix_credit_rules_role_active', 'credit_rules', ['role', 'active'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('context', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_credit_transactions_institution_id_institutions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_transactions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_transactions')),
    sa.UniqueConstraint('user_id', 'source', 'source_id', name='uq_credit_transactions_event')
    )
    op.create_index('ix_credit_transactions_institution_id', 'credit_transactions', ['institution_id'], unique=False)
    op.create_index('ix_credit_transactions_user_id_created_at', 'credit_transactions', ['user_id', 'created_at'], unique=False)
    op.create_table('credit_awards',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('previous_award_id', sa.UUID(), nullable=True),
    sa.Column('innovation', sa.Integer(), nullable=False),
    sa.Column('implementation', sa.Integer(), nullable=False),
    sa.Column('documentation', sa.Integer(), nullable=False),
    sa.Column('presentation', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), sa.Computed('innovation + implementation + documentation + presentation + bonus', persisted=True), nullable=False),
    sa.Column('awarded_by', sa.UUID(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('bonus >= 0', name=op.f('ck_credit_awards_bonus_non_negative')),
    sa.CheckConstraint('documentation >= 0', name=op.f('ck_credit_awards_documentation_non_negative')),
    sa.CheckConstraint('implementation >= 0', name=op.f('ck_credit_awards_implementation_non_negative')),
    sa.CheckConstraint('innovation >= 0', name=op.f('ck_credit_awards_innovation_non_negative')),
    sa.CheckConstraint('presentation >= 0', name=op.f('ck_credit_awards_presentation_non_negative')),
    sa.ForeignKeyConstraint(['awarded_by'], ['users.id'], name=op.f('fk_credit_awards_awarded_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_award_id'], ['credit_awards.id'], name=op.f('fk_credit_awards_previous_award_id_credit_awards'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_credit_awards_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_awards'))
    )
    op.create_index('uq_credit_awards_active_project', 'credit_awards', ['project_id'], unique=True, postgresql_where='superseded_at IS NULL')
    # ### end Alembic commands ###
    _seed_rules()


def _seed_rules() -> None:
    """The V1 rules (ADR-5). Fixed ids so every environment seeds identically.

    Only the student rule has an emitter in Phase 5A — a mentor's award. The
    three faculty events are seeded because the rules list displays them and
    the engine is one engine; their emitters land with the leaderboard.
    """
    rules = sa.table(
        'credit_rules',
        sa.column('id', sa.UUID()),
        sa.column('role', ROLE_ENUM),  # bind as role_enum, not text
        sa.column('event_type', sa.String()),
        sa.column('points', sa.Integer()),
        sa.column('description', sa.String()),
        sa.column('active', sa.Boolean()),
    )
    op.bulk_insert(
        rules,
        [
            {
                'id': uuid.UUID('a1d1f6c2-0a51-4f0e-9c4a-2f0b1d5e7a01'),
                'role': 'student',
                'event_type': 'PROJECT_COMPLETION',
                'points': 300,
                'description': 'Awarded when a project passes final faculty review. '
                'The mentor scores the five components; this is the reference value.',
                'active': True,
            },
            {
                'id': uuid.UUID('a1d1f6c2-0a51-4f0e-9c4a-2f0b1d5e7a02'),
                'role': 'faculty',
                'event_type': 'REVIEW_COMPLETED',
                'points': 80,
                'description': 'Quality-weighted score from a structured review.',
                'active': True,
            },
            {
                'id': uuid.UUID('a1d1f6c2-0a51-4f0e-9c4a-2f0b1d5e7a03'),
                'role': 'faculty',
                'event_type': 'MENTORED_PROJECT_COMPLETED',
                'points': 60,
                'description': 'Mentoring a team through to a completed project.',
                'active': True,
            },
            {
                'id': uuid.UUID('a1d1f6c2-0a51-4f0e-9c4a-2f0b1d5e7a04'),
                'role': 'faculty',
                'event_type': 'PROBLEM_PUBLISHED',
                'points': 10,
                'description': 'Publishing a problem statement to the catalog.',
                'active': True,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_credit_awards_active_project', table_name='credit_awards', postgresql_where='superseded_at IS NULL')
    op.drop_table('credit_awards')
    op.drop_index('ix_credit_transactions_user_id_created_at', table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_institution_id', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index('ix_credit_rules_role_active', table_name='credit_rules')
    op.drop_table('credit_rules')
    # ### end Alembic commands ###
