"""phase 5e profile and identity

The two profile tables and the canonical `users.department`.

One hand edit to the autogenerated output: `downgrade` drops the
`faculty_visibility` type after the table that uses it. Dropping the table alone
leaves the type behind, and the next `upgrade` would then fail trying to create
a type that already exists.

Existing rows are untouched. `users.department` is nullable with no default, so
every account created before this migration stays valid and simply has no
department until its owner sets one; both profile tables start empty, and a user
without a profile row reads as an empty profile.

Revision ID: 5b908971eef5
Revises: 3b73dfca841a
Create Date: 2026-08-14 09:25:48.455556+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '5b908971eef5'
down_revision: str | None = '3b73dfca841a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

FACULTY_VISIBILITY = sa.Enum(
    'public', 'institutional', 'faculty', name='faculty_visibility'
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('faculty_id', sa.String(length=60), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('teaching_focus', sa.String(length=200), nullable=True),
    sa.Column('innovation_focus', sa.String(length=200), nullable=True),
    sa.Column('office_location', sa.String(length=120), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('research_domains', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('open_for_mentorship', sa.Boolean(), nullable=False),
    sa.Column('visibility', FACULTY_VISIBILITY, nullable=False),
    sa.Column('github', sa.String(length=80), nullable=True),
    sa.Column('linkedin', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_faculty_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faculty_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_faculty_profiles_user_id'))
    )
    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(length=160), nullable=True),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('batch', sa.String(length=60), nullable=True),
    sa.Column('roll_number', sa.String(length=60), nullable=True),
    sa.Column('pronouns', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('github', sa.String(length=80), nullable=True),
    sa.Column('linkedin', sa.String(length=80), nullable=True),
    sa.Column('personal_skills', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('public_profile', sa.Boolean(), nullable=False),
    sa.Column('show_contact', sa.Boolean(), nullable=False),
    sa.Column('show_socials', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_student_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_student_profiles_user_id'))
    )
    op.add_column('users', sa.Column('department', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    op.drop_table('student_profiles')
    op.drop_table('faculty_profiles')
    # ### end Alembic commands ###
    FACULTY_VISIBILITY.drop(op.get_bind())
